project:
  type: website
  output-dir: docs

website:
  title: "Yiting Zhong - MUSA 5080 Portfolio"
  navbar:
   left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
          - href: Labs/Lab_1/lab1_template.qmd
            text: Lab 1
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
