project:
  type: website
  output-dir: docs

website:
  title: "Yiting Zhong - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      -text:Weekly Notes
      menu:
      -herf:weekly-notes/week-01-notes.qmd
      text:Week 1

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
